# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempPublicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36)),
                ('permanent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tempmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='djinora_chat.TempPublicUser'),
        ),
    ]
